"""Add MCP and Security tables

Revision ID: 00c7dd7bfeab
Revises: 59460bfd22a3
Create Date: 2026-06-05 16:51:30.522721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00c7dd7bfeab'
down_revision: Union[str, Sequence[str], None] = '59460bfd22a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import os
import json
import uuid

# Resolve config directory path dynamically relative to the migration file
current_dir = os.path.dirname(os.path.abspath(__file__))
config_dir = os.path.abspath(os.path.join(current_dir, "..", "..", "..", "default-config"))

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sse_url', sa.String(), nullable=True),
    sa.Column('sse_headers_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcp_server_id')
    )
    op.add_column('mcp_tools', sa.Column('mcp_server_id', sa.UUID(), nullable=True))
    op.add_column('mcp_tools', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('mcp_tools', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('mcp_tools', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('mcp_tools', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'mcp_tools', 'mcp_servers', ['mcp_server_id'], ['id'])
    op.add_column('skills', sa.Column('source_path', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('is_inferred', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    
    # --- Seeding default configurations (Models & Agents) ---
    bind = op.get_bind()
    
    # 1. Seeding models
    models_file = os.path.join(config_dir, "models.json")
    model_name_to_id = {}
    if os.path.exists(models_file):
        with open(models_file, "r") as f:
            models_data = json.load(f)
        for m in models_data:
            name = m["name"]
            res = bind.execute(sa.text("SELECT id FROM models WHERE name = :name"), {"name": name}).fetchone()
            if res:
                model_id = str(res[0])
                bind.execute(
                    sa.text("""
                        UPDATE models SET
                            hf_repo_id = :hf_repo_id,
                            gguf_filename = :gguf_filename,
                            ram_required_mb = :ram_required_mb,
                            context_size = :context_size,
                            llamacpp_args = :llamacpp_args,
                            parameter_count = :parameter_count,
                            quantization = :quantization,
                            recommended_tasks = :recommended_tasks,
                            llamacpp_version_hash = :llamacpp_version_hash,
                            updated_at = NOW()
                        WHERE id = :id
                    """),
                    {
                        "id": model_id,
                        "hf_repo_id": m.get("hf_repo_id"),
                        "gguf_filename": m.get("gguf_filename"),
                        "ram_required_mb": m.get("ram_required_mb"),
                        "context_size": m.get("context_size"),
                        "llamacpp_args": json.dumps(m.get("llamacpp_args")),
                        "parameter_count": m.get("parameter_count"),
                        "quantization": m.get("quantization"),
                        "recommended_tasks": json.dumps(m.get("recommended_tasks")),
                        "llamacpp_version_hash": m.get("llamacpp_version_hash")
                    }
                )
            else:
                model_id = str(uuid.uuid4())
                bind.execute(
                    sa.text("""
                        INSERT INTO models (
                            id, name, hf_repo_id, gguf_filename, ram_required_mb, context_size,
                            llamacpp_args, parameter_count, quantization, recommended_tasks,
                            llamacpp_version_hash, status, created_at, updated_at
                        ) VALUES (
                            :id, :name, :hf_repo_id, :gguf_filename, :ram_required_mb, :context_size,
                            :llamacpp_args, :parameter_count, :quantization, :recommended_tasks,
                            :llamacpp_version_hash, 'stopped', NOW(), NOW()
                        )
                    """),
                    {
                        "id": model_id,
                        "name": name,
                        "hf_repo_id": m.get("hf_repo_id"),
                        "gguf_filename": m.get("gguf_filename"),
                        "ram_required_mb": m.get("ram_required_mb"),
                        "context_size": m.get("context_size"),
                        "llamacpp_args": json.dumps(m.get("llamacpp_args")),
                        "parameter_count": m.get("parameter_count"),
                        "quantization": m.get("quantization"),
                        "recommended_tasks": json.dumps(m.get("recommended_tasks")),
                        "llamacpp_version_hash": m.get("llamacpp_version_hash")
                    }
                )
            model_name_to_id[name] = model_id

    # 2. Seeding agents
    agents_file = os.path.join(config_dir, "agents.json")
    if os.path.exists(agents_file):
        with open(agents_file, "r") as f:
            agents_data = json.load(f)
        for a in agents_data:
            name = a["name"]
            model_name = a["model_name"]
            model_id = model_name_to_id.get(model_name)
            if not model_id:
                res = bind.execute(sa.text("SELECT id FROM models WHERE name = :name"), {"name": model_name}).fetchone()
                if res:
                    model_id = str(res[0])
                else:
                    continue
            
            res = bind.execute(sa.text("SELECT id FROM agents WHERE name = :name"), {"name": name}).fetchone()
            if res:
                bind.execute(
                    sa.text("""
                        UPDATE agents SET
                            description = :description,
                            model_id = :model_id,
                            system_prompt = :system_prompt,
                            is_orchestrator = :is_orchestrator,
                            is_abstract = :is_abstract,
                            updated_at = NOW()
                        WHERE id = :id
                    """),
                    {
                        "id": str(res[0]),
                        "description": a.get("description"),
                        "model_id": model_id,
                        "system_prompt": a.get("system_prompt"),
                        "is_orchestrator": a.get("is_orchestrator", False),
                        "is_abstract": a.get("is_abstract", False)
                    }
                )
            else:
                agent_id = str(uuid.uuid4())
                bind.execute(
                    sa.text("""
                        INSERT INTO agents (
                            id, name, description, model_id, system_prompt, is_orchestrator, is_abstract, created_at, updated_at
                        ) VALUES (
                            :id, :name, :description, :model_id, :system_prompt, :is_orchestrator, :is_abstract, NOW(), NOW()
                        )
                    """),
                    {
                        "id": agent_id,
                        "name": name,
                        "description": a.get("description"),
                        "model_id": model_id,
                        "system_prompt": a.get("system_prompt"),
                        "is_orchestrator": a.get("is_orchestrator", False),
                        "is_abstract": a.get("is_abstract", False)
                    }
                )
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'is_inferred')
    op.drop_column('skills', 'content_hash')
    op.drop_column('skills', 'source_path')
    op.drop_constraint(None, 'mcp_tools', type_='foreignkey')
    op.drop_column('mcp_tools', 'updated_at')
    op.drop_column('mcp_tools', 'created_at')
    op.drop_column('mcp_tools', 'is_active')
    op.drop_column('mcp_tools', 'content_hash')
    op.drop_column('mcp_tools', 'mcp_server_id')
    op.drop_table('mcp_oauth_tokens')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
