"""Add MCP and Security tables

Revision ID: 0caf4b0cb7bb
Revises: 59460bfd22a3
Create Date: 2026-06-11 20:27:08.462432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0caf4b0cb7bb'
down_revision: Union[str, Sequence[str], None] = '59460bfd22a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import os
import json
import uuid

# Resolve config directory path dynamically relative to the migration file
current_dir = os.path.dirname(os.path.abspath(__file__))
config_dir = os.path.abspath(os.path.join(current_dir, "..", "..", "..", "default-config"))

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('env_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sse_url', sa.String(), nullable=True),
    sa.Column('sse_headers_encrypted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mcp_oauth_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mcp_server_id')
    )
    op.add_column('mcp_tools', sa.Column('mcp_server_id', sa.UUID(), nullable=True))
    op.add_column('mcp_tools', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('mcp_tools', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('mcp_tools', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('mcp_tools', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key('fk_mcp_tools_mcp_servers', 'mcp_tools', 'mcp_servers', ['mcp_server_id'], ['id'])
    op.add_column('skills', sa.Column('source_path', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('skills', sa.Column('is_inferred', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('skills', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    
    # --- Seeding default configurations (Only the 2 new agents if Qwen3.6-35B-A3B-Instruct exists) ---
    bind = op.get_bind()
    
    # Check if Qwen3.6-35B-A3B-Instruct model exists
    model_res = bind.execute(
        sa.text("SELECT id FROM models WHERE name = :name"),
        {"name": "Qwen3.6-35B-A3B-Instruct"}
    ).fetchone()
    
    if model_res:
        model_id = str(model_res[0])
        
        # Load agents from default-config/agents.json
        agents_file = os.path.join(config_dir, "agents.json")
        if os.path.exists(agents_file):
            with open(agents_file, "r") as f:
                agents_data = json.load(f)
            
            for a in agents_data:
                name = a["name"]
                
                # Only seed the 2 new agents
                if name not in ["Security Review Agent", "Skill Inferrer Agent"]:
                    continue
                
                # Check if agent already exists
                agent_res = bind.execute(
                    sa.text("SELECT id FROM agents WHERE name = :name"),
                    {"name": name}
                ).fetchone()
                
                if agent_res:
                    bind.execute(
                        sa.text("""
                            UPDATE agents SET
                                description = :description,
                                model_id = :model_id,
                                system_prompt = :system_prompt,
                                is_orchestrator = :is_orchestrator,
                                is_abstract = :is_abstract,
                                updated_at = NOW()
                            WHERE id = :id
                        """),
                        {
                            "id": str(agent_res[0]),
                            "description": a.get("description"),
                            "model_id": model_id,
                            "system_prompt": a.get("system_prompt"),
                            "is_orchestrator": a.get("is_orchestrator", False),
                            "is_abstract": a.get("is_abstract", False)
                        }
                    )
                else:
                    agent_id = str(uuid.uuid4())
                    bind.execute(
                        sa.text("""
                            INSERT INTO agents (
                                id, name, description, model_id, system_prompt, is_orchestrator, is_abstract, created_at, updated_at
                            ) VALUES (
                                :id, :name, :description, :model_id, :system_prompt, :is_orchestrator, :is_abstract, NOW(), NOW()
                            )
                        """),
                        {
                            "id": agent_id,
                            "name": name,
                            "description": a.get("description"),
                            "model_id": model_id,
                            "system_prompt": a.get("system_prompt"),
                            "is_orchestrator": a.get("is_orchestrator", False),
                            "is_abstract": a.get("is_abstract", False)
                        }
                    )
        else:
            print(f"WARNING: agents.json not found at {agents_file}, skipping agent seeding.")
    else:
        # Log warning in standard migration output
        print("WARNING: Model 'Qwen3.6-35B-A3B-Instruct' not found. Skipping seeding of Security Review Agent and Skill Inferrer Agent.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'created_at')
    op.drop_column('skills', 'is_inferred')
    op.drop_column('skills', 'content_hash')
    op.drop_column('skills', 'source_path')
    op.drop_constraint('fk_mcp_tools_mcp_servers', 'mcp_tools', type_='foreignkey')
    op.drop_column('mcp_tools', 'updated_at')
    op.drop_column('mcp_tools', 'created_at')
    op.drop_column('mcp_tools', 'is_active')
    op.drop_column('mcp_tools', 'content_hash')
    op.drop_column('mcp_tools', 'mcp_server_id')
    op.drop_table('mcp_oauth_tokens')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###

