"""Add llamacpp_version_hash

Revision ID: 1ed9057e747f
Revises: 72788fac6840
Create Date: 2026-05-10 11:02:26.903888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed9057e747f'
down_revision: Union[str, Sequence[str], None] = '72788fac6840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('llamacpp_version_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'llamacpp_version_hash')
    # ### end Alembic commands ###
